{
  "swagger": "2.0",
  "info": {
    "title": "WiserLP API Docs",
    "version": "v1"
  },
  "tags": [{
    "name": "Endpoints"
  }],
  "paths": {
    "/register-client": {
      "post": {
        "tags": [
          "Endpoints"
        ],
        "operationId": "register-client",
        "summary": "Register a new client, you can do so using both username/password or appkey/secret/accessToken/accessTokenSecret, consult the models below",
        "parameters": [
          {
            "name": "User",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User - Authentication with Password"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Register success"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/send-message": {
      "post": {
        "tags": [
          "Endpoints"
        ],
        "operationId": "send-message",
        "summary": "Send a message to any open conversation",
        "parameters": [
          {
            "name": "Message",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Message"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Message sent"
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    }
  },
  "definitions": {
    "User - Authentication with Secret": {
      "required": [
        "username",
        "liveperson_accountid",
        "liveperson_appkey",
        "liveperson_secret",
        "liveperson_accesstoken",
        "liveperson_accesstokensecret"
      ],
      "properties": {
        "username": {
          "type": "string"
        },
        "liveperson_password": {
          "type": "string"
        },
        "liveperson_accountid": {
          "type": "string"
        },
        "liveperson_appkey": {
          "type": "string"
        },
        "liveperson_secret": {
          "type": "string"
        },
        "liveperson_accesstoken": {
          "type": "string"
        },
		    "liveperson_accesstokensecret": {
          "type": "string"
        },
        "new_conversation_webhook": {
          "type": "string"
        },
        "new_file_in_conversation_webhook": {
          "type": "string"
        }
      },
      "example": {
        "username": "John Doe",
        "liveperson_accountid": "1234567890",
        "liveperson_appkey": "1234567890",
        "liveperson_secret": "1234567890",
        "liveperson_accesstoken": "1234567890",
        "liveperson_accesstokensecret": "1234567890",
        "new_conversation_webhook": "https://hooks.zapier.com/hooks/catch/1646904/73834/",
        "new_file_in_conversation_webhook": "https://hooks.zapier.com/hooks/catch/1234443/234234/"
      }
    },
    "User - Authentication with Password": {
      "required": [
        "username",
        "liveperson_accountid",
        "liveperson_password"
      ],
      "properties": {
        "username": {
          "type": "string"
        },
        "liveperson_password": {
          "type": "string"
        },
        "liveperson_accountid": {
          "type": "string"
        },
        "new_conversation_webhook": {
          "type": "string"
        },
        "new_file_in_conversation_webhook": {
          "type": "string"
        }
      },
      "example": {
        "username": "John Doe",
        "liveperson_accountid": "1234567890",
        "liveperson_password": "1234567890",
        "new_conversation_webhook": "https://hooks.zapier.com/hooks/catch/1646904/73834/",
        "new_file_in_conversation_webhook": "https://hooks.zapier.com/hooks/catch/1234443/234234/"
      }
    },
    "Message": {
      "type": "object",
      "required": [
        "credentials",
        "message"
      ],
      "properties": {
        "credentials": {
          "$ref": "#/definitions/User - Authentication with Password"
        },
        "message": {
          "type": "object",
          "required": [
            "dialogId",
            "contentType",
            "message"
          ],
          "properties": {
            "dialogId": {
              "type": "string"
            },
            "contentType": {
              "type": "string"
            },
            "message": {
              "type": "string"
            }
          }
        }
      },
      "example": {
      	"credentials": {
      		"username": "john@doe.com",
      		"liveperson_accountid": "978654321",
      		"liveperson_password": "MySafePasswowrd1234"
      	},
      	"message": {
      		"dialogId": "ABCDE-12345-MNBVC-98765",
      		"contentType": "text/plain",
      		"message": "Hello!"
      	}
      }
    }
  }
}
